### ISSUE TITLE
CT Scan Annotation

### ISSUE THREAD

**Issue by GeorgePearse** [vinbigdata-medical/vindr-lab#3]
Does vindr-lab support annotation of CT exams at the slice/instance level? Thanks

**Comment by Lego1st** [comment]
Hi @GeorgePearse, VinDr Lab has supported CT exams at the slice/instance level. However, we have not had any plan to publicize these features yet.

**Comment by GeorgePearse** [comment]
@Lego1st Thanks for getting back to me. Is it possible to 'scroll through' slices of an exam as you would in a PACs system?

**Comment by Lego1st** [comment]
Yes, of course. You can use the most common tools for reading a CT exams like PACS viewer.
