### ISSUE TITLE
3D Bbox Annotation

### ISSUE THREAD

**Issue by Whiteglad** [vinbigdata-medical/vindr-lab#4]
Hello
Does vindr-lab support 3d bbox annotation for medical image detection?
Thanks

**Comment by Lego1st** [comment]
Yes, we support 3D Bbox annotation. However, this feature is not availabled in the open-source version.
If you are interested in this feature, you can request a demo via our form at https://forms.gle/pFsBMMd2yfLbC1NQ7. We can discuss further.
