### ISSUE TITLE
How to add data to vindr-lab?

### ISSUE THREAD

**Issue by FeryET** [vinbigdata-medical/vindr-lab#6]
Hi.

I've set up a self-hosted vindr-lab instance using the deployment respoistory. So far everything is working but I cannot import any data for my projects.

From my understanding, I should upload data using `${BASE_URL}/dicomweb` address, and then it should be available for users to import. The user in question also has all the access roles vindr exported files have.

Can you please provide further documentation how this should work? Is there anything needed externally not mentioned in the deployment docker-compose file?

**Comment by iamatsundere** [comment]
You shouldn't. We provided a function in the UI, that supports uploading the data. Please visit our [doc](https://vinbigdata-medical.github.io/vindr-lab/).

**Comment by FeryET** [comment]
I found out the problems.

Using the roles you've given, there are some stuff hardcoded in the code, or not explained well that made it confusing for me. I created a master user who had all roles combined, and because there was a hardcoded logic that prevented a PO_PARTNER from importing data, I could not import new data.

As of now, it works correctly.
